2017-11-28 23:46:34,533 [Dummy-1:6888] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-28 23:46:34,536 [Dummy-1:6888] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-28 23:46:34,871 [Dummy-1:7856] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-28 23:46:34,874 [Dummy-1:7856] [django.db.backends:91] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-28 23:46:35,111 [Dummy-1:6068] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-28 23:46:35,115 [Dummy-1:6068] [django.db.backends:91] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-28 23:46:56,072 [Dummy-1:7036] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-28 23:46:56,073 [Dummy-1:7036] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-28 23:47:08,339 [Thread-2:7260] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-28 23:47:08,344 [Thread-2:7260] [django.server:124] [INFO]- "GET / HTTP/1.1" 200 148
2017-11-28 23:47:08,368 [Thread-3:6384] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-28 23:47:08,369 [Thread-3:6384] [django.server:124] [INFO]- "GET /favicon.ico HTTP/1.1" 200 148
2017-11-29 00:00:58,260 [Dummy-1:8916] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:00:58,263 [Dummy-1:8916] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:01:17,028 [Dummy-1:6428] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:01:17,029 [Dummy-1:6428] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:01:20,302 [Thread-2:8888] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:01:20,401 [Thread-2:8888] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 83702
2017-11-29 00:01:20,552 [Thread-3:7928] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:01:20,625 [Thread-3:7928] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 83824
2017-11-29 00:03:53,280 [Dummy-1:7616] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:03:53,283 [Dummy-1:7616] [django.db.backends:91] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:03:56,789 [Dummy-1:8124] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:03:56,792 [Dummy-1:8124] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:04:02,421 [Thread-2:7032] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:04:02,477 [Thread-2:7032] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 83707
2017-11-29 00:04:02,615 [Thread-3:6812] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:04:02,678 [Thread-3:6812] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 83829
2017-11-29 00:04:15,812 [Dummy-1:8616] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:04:15,815 [Dummy-1:8616] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:04:23,013 [Dummy-1:7760] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:04:23,015 [Dummy-1:7760] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:04:25,596 [Thread-2:8368] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:04:25,703 [Thread-2:8368] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 127362
2017-11-29 00:04:25,861 [Thread-3:1944] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:04:25,938 [Thread-3:1944] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 127605
2017-11-29 00:06:03,905 [Dummy-1:8260] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:06:03,907 [Dummy-1:8260] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:06:06,644 [Thread-2:8900] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:06:06,650 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_home' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_home] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,651 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_arch_month' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_arch_month] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,651 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_classfi' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_classfi] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,651 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_tag' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_tag] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_home' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_home] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_arch_month' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_arch_month] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_classfi' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_classfi] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_tag' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_tag] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'is_search' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_search] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'error' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: content. Contents: [<TextNode: u'\\n \\n        '>, <IfNode>, <TextNode: u'\\n        \\n        '>, <django.template.loader_tags.IncludeNode object at 0x0000000003F35A90>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,654 [Thread-2:8900] [django.template:925] [DEBUG]- Exception while resolving variable 'articles' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [articles] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B978>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51208>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003F41630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003E66630>, u'request': <WSGIRequest: GET '/'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/'>}, {'block': <Block Node: content. Contents: [<TextNode: u'\\n \\n        '>, <IfNode>, <TextNode: u'\\n        \\n        '>, <django.template.loader_tags.IncludeNode object at 0x0000000003F35A90>, <TextNode: u'\\n'>]>}, {}]"
2017-11-29 00:06:06,733 [Thread-2:8900] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 139624
2017-11-29 00:06:06,914 [Thread-3:1932] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:06:06,917 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_home' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_home] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,918 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_arch_month' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_arch_month] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,918 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_classfi' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_classfi] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,920 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_tag' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_tag] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: title. Contents: [<TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_home' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_home] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_arch_month' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_arch_month] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_classfi' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_classfi] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_tag' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_tag] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'is_search' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_search] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: path. Contents: [<TextNode: u' \\n   '>, <IfNode>, <TextNode: u'\\n   \\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n   '>, <IfNode>, <TextNode: u'\\n\\n   '>, <IfNode>, <TextNode: u'\\n    \\n\\n  \\n'>]>}]"
2017-11-29 00:06:06,924 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'error' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: content. Contents: [<TextNode: u'\\n \\n        '>, <IfNode>, <TextNode: u'\\n        \\n        '>, <django.template.loader_tags.IncludeNode object at 0x0000000003FE4278>, <TextNode: u'\\n'>]>}]"
2017-11-29 00:06:06,926 [Thread-3:1932] [django.template:925] [DEBUG]- Exception while resolving variable 'articles' in template 'index.html'.
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [articles] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003F1B048>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000003E51278>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003FE44A8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003F28320>, u'request': <WSGIRequest: GET '/favicon.ico'>}, {}, {'e': IOError(2, 'No such file or directory'), 'request': <WSGIRequest: GET '/favicon.ico'>}, {'block': <Block Node: content. Contents: [<TextNode: u'\\n \\n        '>, <IfNode>, <TextNode: u'\\n        \\n        '>, <django.template.loader_tags.IncludeNode object at 0x0000000003FE4278>, <TextNode: u'\\n'>]>}, {}]"
2017-11-29 00:06:07,006 [Thread-3:1932] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 139878
2017-11-29 00:27:24,119 [Dummy-1:7432] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:27:24,122 [Dummy-1:7432] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:27:26,082 [Thread-2:8712] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:27:26,160 [Thread-2:8712] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 127362
2017-11-29 00:27:26,322 [Thread-3:8720] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:27:26,404 [Thread-3:8720] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 127605
2017-11-29 00:28:18,197 [Dummy-1:2712] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:28:18,200 [Dummy-1:2712] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:28:22,664 [Dummy-1:8588] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-11-29 00:28:22,667 [Dummy-1:8588] [django.db.backends:91] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-11-29 00:28:24,918 [Thread-2:8200] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:28:24,973 [Thread-2:8200] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 83707
2017-11-29 00:28:25,151 [Thread-3:6048] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 00:28:25,200 [Thread-3:6048] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 83829
2017-11-29 08:07:11,717 [Thread-5:5284] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 08:07:11,766 [Thread-5:5284] [django.server:124] [ERROR]- "GET / HTTP/1.1" 500 83707
2017-11-29 08:07:11,903 [Thread-6:5840] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 08:07:11,959 [Thread-6:5840] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 83829
2017-11-29 23:50:34,414 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2017-11-29 23:50:34,450 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.021) SELECT VERSION(); args=None
2017-11-29 23:50:34,631 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2017-11-29 23:50:34,631 [Dummy-1:4664] [django.db.backends.schema:111] [DEBUG]- CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); (params None)
2017-11-29 23:50:34,664 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.032) CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); args=None
2017-11-29 23:50:34,665 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=[u'django_migrations']
2017-11-29 23:50:34,671 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=[u'django_migrations']
2017-11-29 23:50:34,671 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=[u'django_migrations']
2017-11-29 23:50:34,673 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=[u'django_migrations']
2017-11-29 23:50:34,734 [Dummy-1:4664] [django.db.backends:91] [DEBUG]- (0.022) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2017-11-29 23:50:36,838 [Dummy-1:7932] [django.db.backends:91] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2017-11-29 23:50:36,838 [Dummy-1:7932] [django.db.backends:91] [DEBUG]- (0.000) SELECT VERSION(); args=None
2017-11-29 23:50:36,871 [Dummy-1:7932] [django.db.backends:91] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2017-11-29 23:50:36,875 [Dummy-1:7932] [django.db.backends:91] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2017-11-29 23:50:39,193 [Thread-2:7504] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,250 [Thread-2:7504] [django.server:124] [INFO]- "GET / HTTP/1.1" 200 17297
2017-11-29 23:50:39,266 [Thread-5:6900] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,269 [Thread-5:6900] [django.server:124] [INFO]- "GET /js/jquery.js HTTP/1.1" 200 17297
2017-11-29 23:50:39,974 [Thread-4:6364] [django.server:124] [INFO]- "GET /static/css/index.css HTTP/1.1" 200 4333
2017-11-29 23:50:39,974 [Thread-3:7796] [django.server:124] [INFO]- "GET /static/css/base.css HTTP/1.1" 200 3339
2017-11-29 23:50:39,983 [Thread-6:8480] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,986 [Thread-7:9180] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,986 [Thread-8:8420] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,987 [Thread-9:3288] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,989 [Thread-10:7736] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,989 [Thread-6:8480] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:39,989 [Thread-11:8348] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:39,993 [Thread-7:9180] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17297
2017-11-29 23:50:39,994 [Thread-8:8420] [django.server:124] [INFO]- "GET /images/img_3.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:39,994 [Thread-9:3288] [django.server:124] [INFO]- "GET /images/img_4.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:39,997 [Thread-11:8348] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17297
2017-11-29 23:50:39,999 [Thread-10:7736] [django.server:124] [INFO]- "GET /images/img_5.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:40,000 [Thread-12:6164] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,002 [Thread-12:6164] [django.server:124] [INFO]- "GET /images/02.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:40,003 [Thread-13:7608] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,006 [Thread-13:7608] [django.server:124] [INFO]- "GET /images/3.jpeg HTTP/1.1" 200 17297
2017-11-29 23:50:40,010 [Thread-14:5032] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,012 [Thread-15:9020] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,015 [Thread-14:5032] [django.server:124] [INFO]- "GET /images/06.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:40,016 [Thread-15:9020] [django.server:124] [INFO]- "GET /images/04.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:40,019 [Thread-16:8588] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,022 [Thread-17:1880] [django.server:124] [INFO]- "GET /static/images/bg.jpg HTTP/1.1" 200 16658
2017-11-29 23:50:40,023 [Thread-16:8588] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17297
2017-11-29 23:50:40,032 [Thread-19:7488] [django.server:124] [INFO]- "GET /static/images/yuanshan.jpg HTTP/1.1" 200 25101
2017-11-29 23:50:40,033 [Thread-20:8200] [django.server:124] [INFO]- "GET /static/images/topbg.jpg HTTP/1.1" 200 10017
2017-11-29 23:50:40,040 [Thread-22:7436] [django.server:124] [INFO]- "GET /static/images/footerbg.png HTTP/1.1" 200 1188
2017-11-29 23:50:40,042 [Thread-23:7892] [django.server:124] [INFO]- "GET /static/images/maintopbg.jpg HTTP/1.1" 200 3503
2017-11-29 23:50:40,046 [Thread-24:9172] [django.server:124] [INFO]- "GET /static/images/time.jpg HTTP/1.1" 200 1327
2017-11-29 23:50:40,046 [Thread-21:8856] [django.server:124] [INFO]- "GET /static/images/navbg.png HTTP/1.1" 200 66208
2017-11-29 23:50:40,049 [Thread-25:9068] [django.server:124] [INFO]- "GET /static/images/rtitbg.png HTTP/1.1" 200 19998
2017-11-29 23:50:40,052 [Thread-26:5732] [django.server:124] [INFO]- "GET /static/images/gz01.png HTTP/1.1" 200 3875
2017-11-29 23:50:40,052 [Thread-27:4720] [django.server:124] [INFO]- "GET /static/images/gz02.png HTTP/1.1" 200 3645
2017-11-29 23:50:40,056 [Thread-28:8180] [django.server:124] [INFO]- "GET /static/images/gz03.png HTTP/1.1" 200 2808
2017-11-29 23:50:40,059 [Thread-29:4724] [django.server:124] [INFO]- "GET /static/images/gz04.png HTTP/1.1" 200 4768
2017-11-29 23:50:40,061 [Thread-30:7604] [django.server:124] [INFO]- "GET /static/images/lanmbq.png HTTP/1.1" 200 1183
2017-11-29 23:50:40,062 [Thread-18:8496] [django.server:124] [INFO]- "GET /static/images/footside.jpg HTTP/1.1" 200 238965
2017-11-29 23:50:40,066 [Thread-31:8688] [django.server:124] [INFO]- "GET /static/images/datepng.png HTTP/1.1" 200 1204
2017-11-29 23:50:40,069 [Thread-32:8224] [django.server:124] [INFO]- "GET /static/images/libg.jpg HTTP/1.1" 200 543
2017-11-29 23:50:40,069 [Thread-33:3784] [django.server:124] [INFO]- "GET /static/images/mainendbg.jpg HTTP/1.1" 200 3512
2017-11-29 23:50:40,306 [Thread-34:8860] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:40,309 [Thread-34:8860] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17297
2017-11-29 23:50:48,380 [Thread-35:3228] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,382 [Thread-35:3228] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17297
2017-11-29 23:50:48,407 [Thread-36:6476] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,410 [Thread-36:6476] [django.server:124] [INFO]- "GET /js/jquery.js HTTP/1.1" 200 17297
2017-11-29 23:50:48,411 [Thread-37:8784] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,413 [Thread-37:8784] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,426 [Thread-38:3364] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,433 [Thread-39:8484] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,434 [Thread-40:7068] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,434 [Thread-38:3364] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17297
2017-11-29 23:50:48,436 [Thread-41:8736] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,440 [Thread-42:8592] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,444 [Thread-43:3184] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,446 [Thread-39:8484] [django.server:124] [INFO]- "GET /images/img_3.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,447 [Thread-44:9028] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,447 [Thread-40:7068] [django.server:124] [INFO]- "GET /images/img_4.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,447 [Thread-41:8736] [django.server:124] [INFO]- "GET /images/img_5.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,450 [Thread-42:8592] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17297
2017-11-29 23:50:48,451 [Thread-43:3184] [django.server:124] [INFO]- "GET /images/06.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,454 [Thread-44:9028] [django.server:124] [INFO]- "GET /images/3.jpeg HTTP/1.1" 200 17297
2017-11-29 23:50:48,454 [Thread-45:7704] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,456 [Thread-46:8656] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,457 [Thread-45:7704] [django.server:124] [INFO]- "GET /images/04.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,457 [Thread-46:8656] [django.server:124] [INFO]- "GET /images/02.jpg HTTP/1.1" 200 17297
2017-11-29 23:50:48,461 [Thread-47:7728] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,463 [Thread-47:7728] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17297
2017-11-29 23:50:48,556 [Thread-48:8668] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:48,558 [Thread-48:8668] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17297
2017-11-29 23:50:49,619 [Thread-49:8640] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:50:49,621 [Thread-49:8640] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17297
2017-11-29 23:54:55,312 [Thread-50:7524] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:54:55,476 [Thread-50:7524] [django.server:124] [ERROR]- "GET /index.html HTTP/1.1" 500 133853
2017-11-29 23:54:55,614 [Thread-51:7532] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:54:55,680 [Thread-51:7532] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 133819
2017-11-29 23:56:22,131 [Thread-56:8912] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,227 [Thread-56:8912] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17306
2017-11-29 23:56:22,250 [Thread-57:4520] [django.server:124] [INFO]- "GET /static/js/jquery.js HTTP/1.1" 200 31033
2017-11-29 23:56:22,253 [Thread-58:8056] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,256 [Thread-58:8056] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,265 [Thread-59:8800] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,266 [Thread-59:8800] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17306
2017-11-29 23:56:22,276 [Thread-60:9184] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,278 [Thread-60:9184] [django.server:124] [INFO]- "GET /images/img_3.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,279 [Thread-62:8664] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,288 [Thread-63:9168] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,289 [Thread-61:5872] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,302 [Thread-64:9052] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,305 [Thread-65:2980] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,306 [Thread-62:8664] [django.server:124] [INFO]- "GET /images/img_5.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,308 [Thread-66:7640] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,312 [Thread-63:9168] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-29 23:56:22,313 [Thread-61:5872] [django.server:124] [INFO]- "GET /images/img_4.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,316 [Thread-67:4616] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,319 [Thread-64:9052] [django.server:124] [INFO]- "GET /images/02.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,321 [Thread-65:2980] [django.server:124] [INFO]- "GET /images/3.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:22,322 [Thread-68:6276] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,325 [Thread-69:5516] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,325 [Thread-66:7640] [django.server:124] [INFO]- "GET /images/06.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,329 [Thread-67:4616] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,332 [Thread-70:6564] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,334 [Thread-68:6276] [django.server:124] [INFO]- "GET /images/04.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:22,335 [Thread-69:5516] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17306
2017-11-29 23:56:22,335 [Thread-70:6564] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:22,464 [Thread-71:4692] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:22,467 [Thread-71:4692] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-29 23:56:36,536 [Thread-72:3152] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,539 [Thread-72:3152] [django.server:124] [INFO]- "GET /w1.html HTTP/1.1" 200 17306
2017-11-29 23:56:36,558 [Thread-73:3996] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,559 [Thread-73:3996] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,565 [Thread-74:8888] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,569 [Thread-74:8888] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17306
2017-11-29 23:56:36,572 [Thread-75:5816] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,576 [Thread-76:6168] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,578 [Thread-78:7768] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,579 [Thread-79:7256] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,579 [Thread-77:6152] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,588 [Thread-80:8008] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,588 [Thread-75:5816] [django.server:124] [INFO]- "GET /images/img_3.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,599 [Thread-76:6168] [django.server:124] [INFO]- "GET /images/img_4.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,601 [Thread-78:7768] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-29 23:56:36,602 [Thread-79:7256] [django.server:124] [INFO]- "GET /images/02.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,604 [Thread-81:7796] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,617 [Thread-77:6152] [django.server:124] [INFO]- "GET /images/img_5.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,625 [Thread-82:8480] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,627 [Thread-80:8008] [django.server:124] [INFO]- "GET /images/3.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:36,628 [Thread-83:9180] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,630 [Thread-84:8736] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,632 [Thread-81:7796] [django.server:124] [INFO]- "GET /images/06.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,634 [Thread-82:8480] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,635 [Thread-83:9180] [django.server:124] [INFO]- "GET /images/04.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:36,635 [Thread-84:8736] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:36,674 [Thread-80:8008] [django.server:124] [ERROR]- "GET /images/3.jpeg HTTP/1.1" 500 59
2017-11-29 23:56:36,674 [Thread-77:6152] [django.server:124] [ERROR]- "GET /images/img_5.jpg HTTP/1.1" 500 59
2017-11-29 23:56:36,714 [Thread-85:4664] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:36,717 [Thread-85:4664] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-29 23:56:37,700 [Thread-86:6160] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,703 [Thread-86:6160] [django.server:124] [INFO]- "GET /w1.html HTTP/1.1" 200 17306
2017-11-29 23:56:37,714 [Thread-87:3812] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,717 [Thread-87:3812] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,743 [Thread-88:8944] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,743 [Thread-89:7992] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,749 [Thread-90:8504] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,750 [Thread-91:8936] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,756 [Thread-92:8956] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,759 [Thread-93:8348] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,766 [Thread-88:8944] [django.server:124] [INFO]- "GET /images/img_2.png HTTP/1.1" 200 17306
2017-11-29 23:56:37,769 [Thread-89:7992] [django.server:124] [INFO]- "GET /images/img_3.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,772 [Thread-90:8504] [django.server:124] [INFO]- "GET /images/img_4.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,773 [Thread-91:8936] [django.server:124] [INFO]- "GET /images/img_5.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,778 [Thread-94:9020] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,778 [Thread-92:8956] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-29 23:56:37,779 [Thread-93:8348] [django.server:124] [INFO]- "GET /images/02.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,786 [Thread-95:7936] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,786 [Thread-96:7736] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,789 [Thread-97:6612] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,796 [Thread-94:9020] [django.server:124] [INFO]- "GET /images/06.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,798 [Thread-98:8468] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,799 [Thread-95:7936] [django.server:124] [INFO]- "GET /images/img_1.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,802 [Thread-96:7736] [django.server:124] [INFO]- "GET /images/3.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:37,802 [Thread-97:6612] [django.server:124] [INFO]- "GET /images/04.jpg HTTP/1.1" 200 17306
2017-11-29 23:56:37,805 [Thread-98:8468] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17306
2017-11-29 23:56:37,855 [Thread-99:8220] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-29 23:56:37,857 [Thread-99:8220] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17306
2017-11-30 00:04:28,726 [Thread-100:8520] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:28,798 [Thread-100:8520] [django.server:124] [ERROR]- "GET /index.html HTTP/1.1" 500 133789
2017-11-30 00:04:28,897 [Thread-101:7600] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:29,016 [Thread-101:7600] [django.server:124] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 133636
2017-11-30 00:04:54,266 [Thread-106:3784] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:54,269 [Thread-106:3784] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17410
2017-11-30 00:04:54,288 [Thread-107:8788] [django.server:124] [INFO]- "GET /static/images/img_1.jpg HTTP/1.1" 200 11574
2017-11-30 00:04:54,295 [Thread-108:4980] [django.server:124] [INFO]- "GET /static/images/img_2.png HTTP/1.1" 200 136957
2017-11-30 00:04:54,301 [Thread-109:7160] [django.server:124] [INFO]- "GET /static/images/img_3.jpg HTTP/1.1" 200 24632
2017-11-30 00:04:54,302 [Thread-110:4100] [django.server:124] [INFO]- "GET /static/images/img_4.jpg HTTP/1.1" 200 6159
2017-11-30 00:04:54,309 [Thread-112:7444] [django.server:124] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 10327
2017-11-30 00:04:54,309 [Thread-113:1208] [django.server:124] [INFO]- "GET /static/images/02.jpg HTTP/1.1" 200 20998
2017-11-30 00:04:54,313 [Thread-111:7916] [django.server:124] [INFO]- "GET /static/images/img_5.jpg HTTP/1.1" 200 33804
2017-11-30 00:04:54,322 [Thread-115:8976] [django.server:124] [INFO]- "GET /static/images/06.jpg HTTP/1.1" 200 16060
2017-11-30 00:04:54,325 [Thread-116:8340] [django.server:124] [INFO]- "GET /static/images/04.jpg HTTP/1.1" 200 14982
2017-11-30 00:04:54,331 [Thread-117:4208] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:54,332 [Thread-114:4244] [django.server:124] [INFO]- "GET /static/images/3.jpeg HTTP/1.1" 200 104229
2017-11-30 00:04:54,335 [Thread-117:4208] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:04:54,487 [Thread-118:4580] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:54,490 [Thread-118:4580] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:04:59,448 [Thread-119:7480] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:59,453 [Thread-119:7480] [django.server:124] [INFO]- "GET /w6.html HTTP/1.1" 200 17410
2017-11-30 00:04:59,463 [Thread-120:5424] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:59,466 [Thread-120:5424] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:04:59,477 [Thread-121:6620] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:59,480 [Thread-121:6620] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:04:59,585 [Thread-122:7904] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:04:59,588 [Thread-122:7904] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:13,095 [Thread-123:8372] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:13,104 [Thread-123:8372] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17410
2017-11-30 00:05:13,131 [Thread-124:8220] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:13,132 [Thread-124:8220] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:13,141 [Thread-125:8760] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:13,144 [Thread-125:8760] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:13,246 [Thread-126:4724] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:13,249 [Thread-126:4724] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:15,160 [Thread-127:7656] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:15,163 [Thread-127:7656] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17410
2017-11-30 00:05:15,176 [Thread-128:2188] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:15,178 [Thread-128:2188] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:15,193 [Thread-129:8452] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:15,194 [Thread-129:8452] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:15,292 [Thread-130:8228] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:15,295 [Thread-130:8228] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:16,878 [Thread-131:8604] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:16,882 [Thread-131:8604] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:05:16,895 [Thread-132:2464] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:16,900 [Thread-132:2464] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:16,913 [Thread-133:8328] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:16,914 [Thread-133:8328] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:17,025 [Thread-134:6248] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:17,029 [Thread-134:6248] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:18,756 [Thread-135:8904] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:18,762 [Thread-135:8904] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:05:18,796 [Thread-136:6900] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:18,799 [Thread-136:6900] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:18,811 [Thread-137:9012] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:18,813 [Thread-137:9012] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:18,914 [Thread-138:7196] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:18,915 [Thread-138:7196] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:20,404 [Thread-139:9064] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:20,411 [Thread-139:9064] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:05:20,440 [Thread-140:8376] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:20,444 [Thread-140:8376] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:20,453 [Thread-141:8728] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:20,456 [Thread-141:8728] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:20,549 [Thread-142:8800] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:20,551 [Thread-142:8800] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:22,453 [Thread-143:7956] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:22,460 [Thread-143:7956] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:05:22,489 [Thread-144:8092] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:22,492 [Thread-144:8092] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:22,502 [Thread-145:8060] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:22,505 [Thread-145:8060] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:22,615 [Thread-146:8676] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:22,618 [Thread-146:8676] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:23,868 [Thread-147:8572] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:23,875 [Thread-147:8572] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:05:23,904 [Thread-148:4664] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:23,911 [Thread-148:4664] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:24,023 [Thread-149:8484] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:24,026 [Thread-149:8484] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:30,869 [Thread-150:4692] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:30,878 [Thread-150:4692] [django.server:124] [INFO]- "GET /newslistpic.html HTTP/1.1" 200 17410
2017-11-30 00:05:30,900 [Thread-151:8988] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:30,903 [Thread-151:8988] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:30,914 [Thread-152:7156] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:30,917 [Thread-152:7156] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:31,023 [Thread-153:7272] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:31,025 [Thread-153:7272] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:05:32,420 [Thread-154:8840] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:32,427 [Thread-154:8840] [django.server:124] [INFO]- "GET /newslistpic.html HTTP/1.1" 200 17410
2017-11-30 00:05:32,444 [Thread-155:6008] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:32,450 [Thread-155:6008] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:32,461 [Thread-156:8644] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:32,464 [Thread-156:8644] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:05:32,553 [Thread-157:832] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:05:32,555 [Thread-157:832] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:06:24,966 [Dummy-1:8524] [django.db.backends:91] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2017-11-30 00:06:24,967 [Dummy-1:8524] [django.db.backends:91] [DEBUG]- (0.001) SELECT VERSION(); args=None
2017-11-30 00:06:25,000 [Dummy-1:8524] [django.db.backends:91] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2017-11-30 00:06:25,005 [Dummy-1:8524] [django.db.backends:91] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2017-11-30 00:06:39,493 [Thread-2:6900] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:39,500 [Thread-2:6900] [django.server:124] [INFO]- "GET / HTTP/1.1" 200 17410
2017-11-30 00:06:39,520 [Thread-3:9012] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:39,523 [Thread-3:9012] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:06:39,805 [Thread-4:6640] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:39,808 [Thread-4:6640] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:06:42,213 [Thread-5:9064] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:42,220 [Thread-5:9064] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:06:42,242 [Thread-6:8376] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:42,244 [Thread-6:8376] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:06:42,256 [Thread-7:8728] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:42,259 [Thread-7:8728] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:06:42,348 [Thread-8:8492] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:42,351 [Thread-8:8492] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:06:45,026 [Thread-9:9016] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:45,029 [Thread-9:9016] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:06:45,042 [Thread-10:8048] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:45,045 [Thread-10:8048] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:06:45,053 [Thread-11:7424] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:45,055 [Thread-11:7424] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:06:45,148 [Thread-12:8988] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:06:45,150 [Thread-12:8988] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:41,029 [Thread-13:5704] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:41,032 [Thread-13:5704] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:10:41,049 [Thread-14:8796] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:41,052 [Thread-14:8796] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:41,059 [Thread-15:8432] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:41,062 [Thread-15:8432] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:41,191 [Thread-16:6616] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:41,194 [Thread-16:6616] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:43,897 [Thread-17:8280] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:43,901 [Thread-17:8280] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:10:43,917 [Thread-18:8444] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:43,920 [Thread-18:8444] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:44,020 [Thread-19:8976] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:44,023 [Thread-19:8976] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:45,335 [Thread-20:8920] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:45,338 [Thread-20:8920] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:10:45,354 [Thread-21:2980] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:45,357 [Thread-21:2980] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:45,365 [Thread-22:5568] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:45,371 [Thread-22:5568] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:45,469 [Thread-23:8660] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:45,470 [Thread-23:8660] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:46,811 [Thread-24:8888] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:46,816 [Thread-24:8888] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:10:46,845 [Thread-25:2724] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:46,848 [Thread-25:2724] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:46,859 [Thread-26:9188] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:46,862 [Thread-26:9188] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:46,957 [Thread-27:4852] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:46,959 [Thread-27:4852] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:48,276 [Thread-28:6128] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:48,282 [Thread-28:6128] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:10:48,315 [Thread-29:6356] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:48,319 [Thread-29:6356] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:48,329 [Thread-30:8872] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:48,335 [Thread-30:8872] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:48,433 [Thread-31:7400] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:48,437 [Thread-31:7400] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:10:50,221 [Thread-32:7052] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:50,229 [Thread-32:7052] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:10:50,252 [Thread-33:7844] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:50,255 [Thread-33:7844] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:50,273 [Thread-34:7868] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:50,276 [Thread-34:7868] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:10:50,362 [Thread-35:7700] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:10:50,365 [Thread-35:7700] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:11:34,473 [Thread-36:1740] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:34,480 [Thread-36:1740] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17410
2017-11-30 00:11:34,516 [Thread-37:8564] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:34,517 [Thread-37:8564] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:34,528 [Thread-38:4344] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:34,530 [Thread-38:4344] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:34,670 [Thread-39:7160] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:34,671 [Thread-39:7160] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:11:35,279 [Thread-40:6620] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:35,280 [Thread-40:6620] [django.server:124] [INFO]- "GET /index.html HTTP/1.1" 200 17410
2017-11-30 00:11:35,292 [Thread-41:8756] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:35,296 [Thread-41:8756] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:35,378 [Thread-42:4160] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:35,381 [Thread-42:4160] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:11:36,538 [Thread-43:3784] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:36,545 [Thread-43:3784] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17410
2017-11-30 00:11:36,572 [Thread-44:8788] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:36,578 [Thread-44:8788] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:36,595 [Thread-45:4980] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:36,598 [Thread-45:4980] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:36,687 [Thread-46:7876] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:36,690 [Thread-46:7876] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:11:37,845 [Thread-47:8708] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:37,851 [Thread-47:8708] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:11:37,878 [Thread-48:3616] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:37,881 [Thread-48:3616] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:11:37,974 [Thread-49:8812] [blog.views:11] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2017-11-30 00:11:37,977 [Thread-49:8812] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:12:14,625 [Dummy-1:9176] [django.db.backends:91] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2017-11-30 00:12:14,625 [Dummy-1:9176] [django.db.backends:91] [DEBUG]- (0.000) SELECT VERSION(); args=None
2017-11-30 00:12:14,663 [Dummy-1:9176] [django.db.backends:91] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2017-11-30 00:12:14,667 [Dummy-1:9176] [django.db.backends:91] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2017-11-30 00:27:23,128 [Thread-2:5064] [django.server:124] [INFO]- "GET /listpic.html HTTP/1.1" 200 17410
2017-11-30 00:27:23,151 [Thread-3:2828] [django.server:124] [INFO]- "GET /images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:27:23,312 [Thread-4:6900] [django.server:124] [INFO]- "GET /images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:27:30,292 [Thread-5:8532] [django.server:124] [INFO]- "GET /jstt/bj/ HTTP/1.1" 200 17410
2017-11-30 00:27:30,319 [Thread-6:7236] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:27:30,417 [Thread-7:7600] [django.server:124] [INFO]- "GET /jstt/bj/images/logo.png HTTP/1.1" 200 17410
2017-11-30 00:28:06,463 [Thread-8:8680] [django.server:124] [INFO]- "GET /jstt/bj/404.html HTTP/1.1" 200 17410
2017-11-30 00:28:06,482 [Thread-9:9172] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:28:06,493 [Thread-10:4244] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 00:28:06,638 [Thread-11:9068] [django.server:124] [INFO]- "GET /jstt/bj/images/logo.png HTTP/1.1" 200 17410
2017-11-30 09:19:18,339 [Thread-12:5140] [django.server:124] [INFO]- "GET /jstt/bj/404.html HTTP/1.1" 200 17410
2017-11-30 09:19:18,361 [Thread-13:7064] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 09:19:18,374 [Thread-14:5568] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17410
2017-11-30 09:19:18,559 [Thread-15:9184] [django.server:124] [INFO]- "GET /jstt/bj/images/logo.png HTTP/1.1" 200 17410
2017-11-30 09:24:52,214 [Thread-18:7124] [django.server:124] [INFO]- "GET /jstt/bj/404.html HTTP/1.1" 200 17418
2017-11-30 09:24:52,233 [Thread-19:7736] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17418
2017-11-30 09:24:58,746 [Thread-20:7444] [django.server:124] [INFO]- "GET /jstt/bj/index.html HTTP/1.1" 200 17418
2017-11-30 09:24:58,763 [Thread-21:7256] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17418
2017-11-30 09:24:58,775 [Thread-22:6092] [django.server:124] [INFO]- "GET /jstt/bj/images/xifu.jpeg HTTP/1.1" 200 17418
2017-11-30 09:26:25,579 [Thread-24:4868] [django.server:124] [INFO]- "GET /jstt/bj/index.html HTTP/1.1" 200 17426
2017-11-30 09:26:26,142 [Thread-25:2980] [django.server:124] [INFO]- "GET /static/images/xifu.jpeg HTTP/1.1" 200 264305
2017-11-30 09:26:38,059 [Thread-30:7272] [django.server:124] [INFO]- "GET /jstt/bj/w5.html HTTP/1.1" 200 17426
2017-11-30 09:30:34,519 [Thread-31:7832] [django.server:124] [INFO]- "GET /favicon.ico HTTP/1.1" 200 17426
2017-11-30 09:37:41,335 [Thread-37:6932] [django.server:124] [INFO]- "GET /jstt/bj/w5.html HTTP/1.1" 200 17357
2017-11-30 09:38:07,217 [Thread-43:3996] [django.server:124] [INFO]- "GET /favicon.ico HTTP/1.1" 200 17357
2017-11-30 09:38:57,108 [Thread-49:8440] [django.server:124] [INFO]- "GET /jstt/bj/w5.html HTTP/1.1" 200 17345
2017-11-30 09:41:09,746 [Thread-54:8436] [django.server:124] [INFO]- "GET /w5.html HTTP/1.1" 200 17345
2017-11-30 09:41:21,612 [Thread-59:7512] [django.server:124] [INFO]- "GET /about.html HTTP/1.1" 200 17345
